"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rect_1 = require("./Rect");
var myShape = new Shape_1.Shape(10, 15);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(10, 15, 20);
console.log(myCircle.getInfo());
var myRect = new Rect_1.Rect(0, 0, 3, 7);
console.log(myRect.getInfo());
